version: "3.8"
services:
  car_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: car_hire
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root-pw
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: car_mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root-pw
    ports:
      - "8080:80"
    networks:
      - my-network

  car_redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my-network


  car_couchdb:
    image: couchdb:latest
    environment:
      COUCHDB_USER: couchdb
      COUCHDB_PASSWORD: coconut
    ports:
      - "5984:5984"
    volumes:
      - ./dbdata:/opt/couchdb/data
    networks:
      - my-network


volumes:
  redis_data:
  my-db:


networks:
  my-network:
    external: true
    name: my-network

